### ISSUE TITLE
[Feature Request] Snow/Ice

### ISSUE THREAD

**Issue by milkev** [InZan123/Unloaded-Activity-Fabric#15]
**Description**
It would be cool if snow and ice could be part of the unloaded activity. It would really help the feeling of time passing when travelling back to cold biomes.

**Compat with Fabric Seasons**
If this is to be implemented, it would be cool if it also based itself off of what season it is from fabric seasons. My understanding is that they have it as a "maybe planned" feature but im not sure. Either way, if this was implemented here it would be a nice little compatability. The non-compat feature request here i think would still be great even without taking fabric seasons into account.

**Comment by InZan123** [comment]
I've actually already added snow and ice for unloaded activity. Though there are still a few more things I wanna do so it might take a while before I release a new update.

As for compat with Fabric Seasons, I plan to eventually support it as well as other mods but right now I would like to make my mod perfect with the vanilla game first before I focus on supporting other mods.

**Comment by milkev** [comment]
fair enough!
looking forward to the next release then

**Comment by InZan123** [comment]
v0.5.0 has now been released with snow/ice support.
