### ISSUE TITLE
[Question] Is it support this mod?

### ISSUE THREAD

**Issue by IntM4rco** [InZan123/Unloaded-Activity-Fabric#16]
I wonder if with the Realistic Sleep mod during the change from night to day the time spent is not duplicated because both your mod and Realistic Sleep calculate the time spent sleeping. 

https://modrinth.com/mod/realisticsleep

**Comment by InZan123** [comment]
it's compatible.
My mod detects whenever there's a big time difference from when something was last ticked. Realistic Sleep smoothly skips the night which means my mod will not detect it.
