### ISSUE TITLE
No XP For Smelting

### ISSUE THREAD

**Issue by RobertHDPotatoes** [InZan123/Unloaded-Activity-Fabric#17]
Fabric 1.20.2

I'm unsure about loading/unloading chunks, but if you sleep through the night while you are smelting something, all smelted items give no experience when removed from the furnace. I don't know if this is an oversight or a limitation, but I thought I'd bring it to your attention in case you weren't aware. If this could be fixed, that'd be awesome!

**Comment by InZan123** [comment]
I've looked into it and it seems to only affect 1.20.2 as far as I am aware. I will try to quickly fix this and publish the new version.

**Comment by InZan123** [comment]
I have updated the mod and it should be up on modrinth and curseforge in a bit. Thanks for bringing this to my attention.
