### ISSUE TITLE
[1.19.2] Crash when furnace is loaded

### ISSUE THREAD

**Issue by Traktool** [InZan123/Unloaded-Activity-Fabric#5]
Hi, thanks for this mod, it's a must have!

Just a problem, I'm playing with somes friends on a personnal modpack that I've done.
We're been playing for some hours without any problem, bug now when we load our base, where some furnaces are empty, the server just crash. If we restart, no problem, but if we try to connect, the server instantly crash, cause the furnace is loaded by the server

Here the crash report: https://mclo.gs/nppwU2K

Minecraft 1.19.2
Fabric 0.14.19
Mod version 0.3.0

**Comment by InZan123** [comment]
I looked into it and it seems like when you put an item which isn't smeltable in the furnace then it will crash once you unload and load it in again. 

For the time being you could try disabling the "Update Furnaces" option. Find "unloaded-activity.json" in the config folder inside the server folder. Then you just set "updateFurnace" to false.

**Comment by Traktool** [comment]
Yes, that's what I've done, just disabled the furnace update

And yeah, my friend wanted to smelt adamantite from a mod, adamantite that is not smeltable

**Comment by dlfnn** [comment]
https://modrinth.com/mod/discerning-furnace

**Comment by InZan123** [comment]
Version 0.4.0 has now been released and this bug is fixed.
